version: '3'
services:
  nginx-app:
    container_name: nginx_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    image: shomikhan/nginx-app:latest
    volumes:
      - ./index.html:/usr/share/nginx/html/mywebsite/index.html