apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:                # ✅ Selector দরকার pod match করার জন্য
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: shomikhan/nginx-app:latest
          ports:
            - containerPort: 80
