apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: LoadBalancer  # Service type (LoadBalancer level)
  ports:
    - port: 8000          # Service port
      targetPort: 80      # Container-এর port
